

#gameboard
BOARD_ROWS = 25
BOARD_COLS = 50


CELL_SIZE = 20 # pixels per cell
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

#solider
SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part
SOLDIER_START = 0, 0
SOLDIER_MOVE = 0, 0


#flag
FLAG_ROWS = 3
FLAG_COLS = 4

flag_row = BOARD_ROWS - FLAG_ROWS
flag_col = BOARD_COLS - FLAG_COLS
FLAG_LOCATION = flag_col*CELL_SIZE, flag_row*CELL_SIZE

#mines
MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3

#grass
GRASS_SIZE = 3*CELL_SIZE,3*CELL_SIZE

#state
RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3

#colors
RED = (255, 89, 94)
GREEN = (138, 201, 38)
BLUE = (25, 130, 196)
ORANGE = (255, 202, 58)
VIOLET = (106, 76, 147)
BLACK = (0, 0, 0)
BACKGROUND_COLOR = (254, 252, 252)

#message
FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = BLACK
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))

WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))

WELCOME_MESSAGE = "Welcome to The Flag game.\nHave Fun!"
WELCOME_FONT_SIZE = int(0.05 * WINDOW_HEIGHT)
WELCOME_COLOR = (254, 252, 252)
WELCOME_LOCATION = \
    (SOLDIER_COLS*CELL_SIZE, SOLDIER_ROWS)

